---
version: "2.0"
services:
  app:
    image: debian:12
    expose:
      - port: 22 # доступ по SSH по публичному ключу (без пароля)
        as: 22
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true
    command:
      - bash
      - "-c"
      - "apt-get update && apt-get install wget -y && cd ~ && wget https://raw.githubusercontent.com/Andrey36652/textgen-akash/main/install-and-run.sh && source install-and-run.sh"
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          - size: 2Gi
        # gpu:
        #   units: 1
        #   attributes:
        #     vendor:
        #       nvidia:
                #- model: rtx3090
                #- model: rtx4090
                #- model: rtx3080
                #- model: rtx3070
                #- model: rtx3060
                #- model: rtx3060ti
  placement:
    akash:
      pricing:
        app:
          denom: uakt
          amount: 1000000
deployment:
  app:
    akash:
      profile: app
      count: 1
